version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gdg-recruitment-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gdg_recruitment
      POSTGRES_USER: gdg_admin
      POSTGRES_PASSWORD: gdg_secure_password_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gdg-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gdg-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gdg.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - gdg-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  gdg-network:
    driver: bridge
